# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: theCluelessGuru
email: jtronlabs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  theCluelessGuru, a site to discuss software, hardware, and inner peace
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jtronlabs.github.io/blog" # the base hostname & protocol for your site
twitter_username: jtronlabs
github_username:  jtronlabs

# Build settings
markdown: kramdown
